/*
Deployment script for C:\USERS\GUNTUR\DOCUMENTS\DB_CBV.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\GUNTUR\DOCUMENTS\DB_CBV.MDF"
:setvar DefaultFilePrefix "C_\USERS\GUNTUR\DOCUMENTS\DB_CBV.MDF_"
:setvar DefaultDataPath "C:\Users\Guntur\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Guntur\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[tbl_klaim]...';


GO
CREATE TABLE [dbo].[tbl_klaim] (
    [KODE_KLAIM]        VARCHAR (10)  NOT NULL,
    [NO_BUKU]           VARCHAR (50)  NULL,
    [KODE_JENIS]        VARCHAR (25)  NOT NULL,
    [NAMA_LENGKAP]      VARCHAR (50)  NULL,
    [TEMPAT_LAHIR]      VARCHAR (25)  NULL,
    [TANGGAL_LAHIR]     DATE          NULL,
    [JENIS_KELAMIN]     VARCHAR (20)  NOT NULL,
    [PEKERJAAN]         VARCHAR (25)  NULL,
    [ALAMAT_LENGKAP]    VARCHAR (255) NULL,
    [NO_TELEPON]        VARCHAR (14)  NULL,
    [SAKIT_DIDERITA]    VARCHAR (50)  NULL,
    [RUMAH_SAKIT]       VARCHAR (50)  NULL,
    [LAMA_RAWAT]        VARCHAR (3)   NULL,
    [TANGGAL_MENINGGAL] VARCHAR (15)  NULL,
    [ID_ANGGOTA]        VARCHAR (5)   NOT NULL
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [NO_BUKU];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [NAMA_LENGKAP];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [TEMPAT_LAHIR];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [TANGGAL_LAHIR];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [PEKERJAAN];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [ALAMAT_LENGKAP];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [NO_TELEPON];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [SAKIT_DIDERITA];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [RUMAH_SAKIT];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [LAMA_RAWAT];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[tbl_klaim]...';


GO
ALTER TABLE [dbo].[tbl_klaim]
    ADD DEFAULT NULL FOR [TANGGAL_MENINGGAL];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
